### ISSUE TITLE
Make all posts public?

### ISSUE THREAD

**Issue by oriol-corbella** [YoraiLevi/SetFacebookPostsPrivate#2]
Hello, 
I would need to make all my posts "public", instead of "private". How could this be done?

Thanks.

**Comment by YoraiLevi** [comment]
This can be easily done, It's a matter of changing 3 constants If I remember correctly.
I'll make a new branch with this feature until I make it a choice

**Comment by YoraiLevi** [comment]
> Hello,
> I would need to make all my posts "public", instead of "private". How could this be done?
> 
> Thanks.

**Comment by oriol-corbella** [comment]
Thanks! I've been looking the code, but I have not skills enough. I saw you use the name of the PNG as a reference to make it Public, Private or Only Friends?

**Comment by YoraiLevi** [comment]
I didn't document the code much and it is a great mess. I still remember the procedure I took when writing it so it was fairly simple.

I made you a script that can make posts public instead of private [install it here](https://github.com/YoraiLevi/SetFacebookPostsPrivate/raw/SetPublic/GreaseMonkeySetFacebookPrivate.user.js) I tested it on only 1 post, so if you have issues do update me.
Hopefully if I made it correctly changing these constant/making it a choice should make it 
https://github.com/YoraiLevi/SetFacebookPostsPrivate/blob/ef96a6a1aade6a0f12a91fd3ddaa964882a720bc/GreaseMonkeySetFacebookPrivate.user.js#L75
https://github.com/YoraiLevi/SetFacebookPostsPrivate/blob/ef96a6a1aade6a0f12a91fd3ddaa964882a720bc/GreaseMonkeySetFacebookPrivate.user.js#L211

https://github.com/YoraiLevi/SetFacebookPostsPrivate/tree/SetPublic

The code itself it separated into 2 main parts based on which facebook page you're at.
If you are in the activity log it injects the GUI and iteratively opens posts found.
If you are in a post page it changes its privacy
(and a third if you commented on a group/someone elses posts it tries to ignore the page)

The images are there to make it language agnostic when choosing the correct privacy settings, in this "new" code i gathered dictionaries for each privacy mode. Previously some images were `hardcoded` to select search for the private mode...

**Comment by oriol-corbella** [comment]
Thank you very much!

I'm trying it on Google Chrome but when I click on "Open All" or "Open Range", nothing happens after that... :/

**Comment by YoraiLevi** [comment]
> Thank you very much!
> 
> I'm trying it on Google Chrome but when I click on "Open All" or "Open Range", nothing happens after that... :/
> 

Does the original set to private works? or is it the same, doing nothing?

**Comment by YoraiLevi** [comment]
You are correct! I hadn't checked if the automatic mechanism works which I broke! (a global wasn't available in the context) I fixed it. try[ installing again](https://github.com/YoraiLevi/SetFacebookPostsPrivate/raw/SetPublic/GreaseMonkeySetFacebookPrivate.user.js)

**Comment by oriol-corbella** [comment]
Thanks, now it runs, but it doesn't change the privacy.
It closes the tab without doing anything.

I tried with both scripts (the original setPrivate ans setPublic). Thanks!

Maybe it has nothing to do, but I have to select any "document" option on "Run at" in Settins, to be able to see the script's window.

**Comment by YoraiLevi** [comment]
> Thanks, now it runs, but it doesn't change the privacy.
> It closes the tab without doing anything.
> 
> I tried with both scripts (the original setPrivate ans setPublic). Thanks!
> 
> Maybe it has nothing to do, but I have to select any "document" option on "Run at" in Settins, to be able to see the script's window.

😅 Honestly first time remotely debugging code that someone else uses... I will add logging so we can determine where it fails...

**Comment by oriol-corbella** [comment]
Haha, and I am very thankful for this! Thanks!

It's my first time working with Tampermonkey, and still learning how does it work... :S

**Comment by YoraiLevi** [comment]
Added some logging and a button to download the logs. Hopefully this will let me know where it fails... not why tho. honestly idk what to even log to know why. same url as before to update [link](https://github.com/YoraiLevi/SetFacebookPostsPrivate/raw/SetPublic/GreaseMonkeySetFacebookPrivate.user.js)
we'll see i guess

**Comment by oriol-corbella** [comment]
Hey,
Sorry I was away from my computer these days. Hehe.

Thanks, now I tried it but nothing happens when I click "Open All" or "Open
Range". The log I get is just "[]".

Missatge de Yorai Levi <notifications@github.com> del dia dc., 10 de febr.
2021 a les 22:22:

**Comment by YoraiLevi** [comment]
@ruccc Is your facebook display language English? if not, can you try to change it?

Edit: I see someone has reported on greasefork too that the original script doesn't work! It seems like facebook has changed a certain css selector that I relied on, I am fixing it. I hope it'll work finally.
